import type { LiveEventRow, LiveMetrics, TraceFlowStep } from "./live-types";

/** Mock data aligned with docs/architecture/agent-voir-dashboard-01.png */
export const mockLiveMetrics: LiveMetrics = {
  requestsTotal: 18240,
  errors: 132,
  toolCalls: 1243,
  finalAnswers: 8912,
  blocked: 45,
  cacheHits: 3802,
  tokensIn: 174320,
  tokensOut: 82460,
  activeRequests: 12,
  costUsd: 1.82,
  cacheHitRate: 0.312,
  p50LatencyMs: 620,
  p95LatencyMs: 1420,
  p99LatencyMs: 3210,
};

export const mockLiveRows: LiveEventRow[] = [
  {
    traceId: "trace_9b8d7f",
    spanId: "span_llm_001",
    time: "10:24:31.245",
    agent: "research-agent",
    user: "user_42",
    reqResp: "POST /v1/responses → 200 OK",
    status: 200,
    provider: "OpenAI",
    model: "gpt-4.1-mini",
    responseType: "TOOL_CALL",
    nextAction: "Execute github.search_issues",
    tool: "github.search_issues",
    terminal: false,
    tags: ["tool-call", "review"],
    tokensIn: 1420,
    tokensOut: 0,
    durationMs: 1120,
    costUsd: 0.0032,
    otelStatus: "exported",
    datadogStatus: "indexed",
  },
  {
    traceId: "trace_9b8d7f",
    spanId: "span_tool_001",
    time: "10:24:32.401",
    agent: "research-agent",
    user: "user_42",
    reqResp: "TOOL github.search_issues → 200 OK",
    status: 200,
    provider: "AgentVoir Tools",
    model: "github.search_issues",
    responseType: "TOOL_RESULT",
    nextAction: "Send result to LLM",
    tool: "github.search_issues",
    terminal: false,
    tags: ["tool-result"],
    tokensIn: 0,
    tokensOut: 0,
    durationMs: 430,
    costUsd: 0,
    otelStatus: "exported",
    datadogStatus: "indexed",
  },
  {
    traceId: "trace_9b8d7f",
    spanId: "span_llm_002",
    time: "10:24:33.812",
    agent: "research-agent",
    user: "user_42",
    reqResp: "POST /v1/responses → 200 OK",
    status: 200,
    provider: "OpenAI",
    model: "gpt-4.1-mini",
    responseType: "FINAL_ANSWER",
    nextAction: "Return to client",
    tool: "—",
    terminal: true,
    tags: ["final-answer"],
    tokensIn: 2180,
    tokensOut: 640,
    durationMs: 1890,
    costUsd: 0.0061,
    otelStatus: "exported",
    datadogStatus: "indexed",
  },
  {
    traceId: "trace_2f5c1a",
    spanId: "span_llm_009",
    time: "10:24:28.102",
    agent: "support-agent",
    user: "user_17",
    reqResp: "POST /v1/chat/completions → 403",
    status: 403,
    provider: "OpenAI",
    model: "gpt-4.1-mini",
    responseType: "GUARDRAIL_BLOCK",
    nextAction: "Policy denied",
    tool: "—",
    terminal: true,
    tags: ["policy-blocked", "error"],
    tokensIn: 890,
    tokensOut: 0,
    durationMs: 45,
    costUsd: 0,
    otelStatus: "exported",
    datadogStatus: "indexed",
  },
  {
    traceId: "trace_a1c3e9",
    spanId: "span_cache_001",
    time: "10:24:27.880",
    agent: "cache-demo-agent",
    user: "user_03",
    reqResp: "POST /v1/chat/completions → 200 OK",
    status: 200,
    provider: "OpenAI",
    model: "gpt-4.1-mini",
    responseType: "CACHE_RESPONSE",
    nextAction: "Return cached answer",
    tool: "—",
    terminal: true,
    tags: ["cache-hit"],
    tokensIn: 420,
    tokensOut: 180,
    durationMs: 12,
    costUsd: 0,
    otelStatus: "exported",
    datadogStatus: "indexed",
  },
];

export const mockTraceFlow: TraceFlowStep[] = [
  {
    step: 1,
    kind: "User Request",
    status: "complete",
    durationMs: 8,
    nextAction: "Route to LLM",
  },
  {
    step: 2,
    kind: "LLM Call",
    responseType: "TOOL_CALL",
    status: "complete",
    durationMs: 1120,
    nextAction: "Execute github.search_issues",
    tool: "github.search_issues",
  },
  {
    step: 3,
    kind: "Tool Execution",
    responseType: "TOOL_RESULT",
    status: "complete",
    durationMs: 430,
    nextAction: "Send result to LLM",
    tool: "github.search_issues",
  },
  {
    step: 4,
    kind: "LLM Call",
    responseType: "FINAL_ANSWER",
    status: "complete",
    durationMs: 1890,
    nextAction: "Return to client",
  },
  { step: 5, kind: "Response Returned", status: "complete", durationMs: 4, nextAction: "Done" },
];

export const mockToolCallJson = JSON.stringify(
  {
    function: "github.search_issues",
    arguments: {
      owner: "agentvoir",
      repo: "agentvoir",
      query: "is:open label:bug",
      per_page: 5,
    },
  },
  null,
  2,
);

export const mockTraceDetail = {
  traceId: "trace_9b8d7f",
  agentId: "research-agent",
  userId: "user_42",
  status: "complete",
  startedAt: "10:24:31.245",
  durationMs: 3452,
  costUsd: 0.0093,
  tags: ["tool-call", "review"],
  tokensIn: 3600,
  tokensOut: 640,
  budgetRemaining: 315780,
  spanId: "span_llm_001",
  otelStatus: "exported",
  datadogStatus: "indexed",
};
