ALTER TABLE agents
  ADD COLUMN IF NOT EXISTS cache_mode TEXT NOT NULL DEFAULT 'exact_only',
  ADD COLUMN IF NOT EXISTS cache_ttl_seconds BIGINT NOT NULL DEFAULT 86400,
  ADD COLUMN IF NOT EXISTS semantic_cache_allowed BOOLEAN NOT NULL DEFAULT false;
